name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          stale-pr-message: 'This PR hasn not seen any activity on the last 30 days, so it will be marked as inactive and will be closed in 7 days unless there are any updates.'
          days-before-stale: 30
          days-before-close: 7
          stale-pr-label: Inactive
          exempt-pr-labels: Under review