name: Plugin Validation

on:
  pull_request:
    branches:
      - "master"
    # Add this later on
    # paths:
    #   - 'community-plugins.json'

jobs:
  lint-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS 14
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Validate Plugin
        run: node '.github/scripts/validatePlugin.mjs'

