name: Validate Plugin Entry

on:
  pull_request_target:
    branches:
      - master
    paths:
      - community-plugins.json

jobs:
  plugin-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"
      - uses: actions/setup-node@v2
      - uses: actions/github-script@v6
        with:
          script: |
            const script = require('./validation-plugin.js');
            return await script({github, context, core});
    permissions:
      contents: write
      issues: write
      pull-requests: write